
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[591] =
    {   0,
        0,    0,   22,   20,   21,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   16,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   17,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   14,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   18,    0,    0,   10,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    1,    0,    0,   19,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   11,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    1,    1,    6,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,   10,
       11,   12,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   22,   35,   22,
        1,    1,    1,    1,   36,    1,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    1,    1,    1,
        1,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    1,    7
    } ;

static yyconst flex_int16_t yy_base[707] =
    {   0,
        0,   33,  965,  966,  966,    0,  948,  937,    0,  941,
        2,  929,  931,    4,  942,  926,  931,  936,  943,  938,
      927,  939,  926,  917,  933,  916,  922,  929,  941,  913,
      913,  919,  910,  919,  927,  930,  933,  913,  906,  904,
      912,   10,  919,  916,  917,   51,  912,  898,  896,  890,
      902,  913,    0,  906,  909,  890,  904,  887,  900,  897,
      893,  884,  883,  885,  899,  882,  893,  883,  879,    0,
      888,    0,  885,  888,  887,   76,  897,    0,  889,  886,
      887,  882,  873,  966,  876,  866,  874,  877,  861,  869,
      874,  860,  858,  856,  849,  869,    1,  854,  857,  855,

      878,  865,  859,  851,  849,  860,  844,  849,    2,  836,
      848,  841,  846,  866,  854,  845,  863,  840,  836,  851,
      833,  849,  831,  824,  842,  820,  852,  827,  849,    0,
      834,  830,  820,   85,  835,  817,  817,  831,  817,  823,
      814,  839,    0,  805,  838,  824,  809,    4,  808,  821,
        5,  812,  800,  812,  817,  802,  796,  814,  825,  966,
      825,   25,  790,  814,  791,  812,  796,  810,  793,  804,
      794,  790,    0,  814,  796,  803,  802,  784,  782,  776,
      802,  772,    0,  780,  804,  801,    0,  785,  966,  799,
        0,  800,  772,  772,  784,  769,  771,    0,  793,    0,

      759,  771,  791,  771,  761,  769,  774,  760,  758,  756,
      749,   26,  770,  762,  753,   36,  762,  765,  966,  743,
      775,  775,    0,   38,  740,  751,   46,  738,    0,  755,
      770,  744,  752,  739,  765,  760,  730,  763,   48,  736,
      752,  734,  750,  732,  725,  743,  721,  753,  751,    0,
      739,  725,  737,   53,  722,  725,  723,  742,  744,    0,
      743,  742,    0,  708,  720,  739,    0,  705,  737,  728,
       54,  704,  726,  725,  729,  731,  966,  697,   57,  728,
        0,  729,  709,  714,  699,  693,  711,  722,  966,   59,
      688,  721,  720,  694,  716,    0,  701,  697,  687,  707,

      712,  708,  710,  705,  675,  708,  702,  672,  966,  704,
      683,  701,    0,  675,  680,  681,  692,  696,    0,   70,
      663,   72,  670,  682,  667,  669,  691,    0,  657,   74,
       77,  658,   80,  655,  679,  656,  677,   47,  681,  683,
      676,  966,  648,    0,  966,  647,  680,   90,  645,  662,
      677,  650,  672,   91,  640,  672,    0,  638,  669,    0,
      670,  644,  652,  639,  661,  631,  662,    0,  661,    0,
      635,  660,    0,  626,  638,  658,  638,  647,  630,  647,
      650,  651,   98,  650,    0,  616,  640,   99,  648,   64,
      646,    0,  612,  640,  610,  105,  609,  106,  610,  632,

      631,  966,  605,  108,  604,  111,  603,  620,  601,  634,
      112,  607,  613,  603,  631,  114,  966,  628,  626,    0,
      593,  605,  623,    0,  113,  966,  619,  589,  966,  588,
      620,    0,  586,  617,    0,  591,  596,  597,  614,    0,
      580,  612,    0,  578,  602,  576,  117,  607,    0,  608,
      581,  593,    0,  966,  118,  571,  570,  603,  119,  568,
      599,    0,  966,  566,  594,  564,  122,  563,  580,  595,
      568,  559,  558,  570,  588,    0,  123,  555,  124,  575,
      582,  587,  584,    0,  550,  125,  579,    0,  539,  126,
      534,  966,  529,  553,    0,  513,  533,  127,  537,  498,

      487,  512,  130,  473,  501,    0,  463,  490,    0,  966,
      478,  471,  435,  458,    0,  419,  443,    0,  403,  398,
      406,  420,    0,  131,  132,  414,    0,  376,  361,  133,
      354,  966,  966,  347,  134,  342,  337,  332,  327,  353,
      137,  307,  330,    0,  325,    0,  286,  279,  303,    0,
      265,  294,    0,  253,  247,  139,  271,    0,  228,  140,
      224,  144,  216,  211,  205,  199,  216,    0,  177,  201,
        0,  163,  175,    0,  141,  140,  137,  145,  135,  134,
      128,  127,  153,    0,  119,  115,   48,   42,   21,  966,
      182,  185,  189,  191,  193,  197,  202,  205,  207,  211,

      214,  218,  221,  223,  225,  227,  229,  233,  239,  241,
      245,  250,  253,  258,  262,  265,  267,  272,  274,  276,
      281,  283,  287,  290,  295,  299,  304,  307,  309,  313,
      316,  320,  323,  327,  332,  335,  337,  341,  344,  346,
      348,  353,  355,  357,  361,  366,  371,  376,  381,  384,
      388,  391,  395,  398,  400,  402,  404,  406,    0,  410,
      415,  418,  422,  427,  432,  437,  440,  444,  447,  449,
      453,  456,  460,  463,  465,  469,  472,  476,  479,  483,
      486,  488,  492,  497,  502,  507,  512,  515,  517,  521,
      524,  526,  528,  532,  537,  542,  547,  550,  554,  557,

      559,  563,  568,  573,  576,  580
    } ;

static yyconst flex_int16_t yy_def[707] =
    {   0,
      591,  591,  590,  590,  590,  592,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  593,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  593,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  594,
      590,  590,  590,  590,  590,  590,  590,  595,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  596,  590,  590,  590,  590,  590,

      590,  590,  590,  590,  590,  590,  590,  590,  590,  597,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  596,  590,  590,  590,  598,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  599,  597,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  600,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  601,  590,  590,  590,  590,  590,  590,  590,
      590,  602,  603,  590,  590,  590,  604,  590,  590,  590,
      605,  590,  590,  590,  590,  590,  590,  606,  590,  607,

      600,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      608,  590,  590,  590,  590,  590,  590,  590,  590,  602,
      609,  590,  610,  590,  611,  590,  590,  612,  613,  590,
      590,  590,  590,  590,  614,  590,  615,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  608,  590,  590,  616,
      590,  590,  590,  590,  590,  590,  590,  590,  609,  617,
      618,  590,  619,  611,  590,  590,  620,  612,  621,  590,
      590,  590,  590,  590,  590,  614,  590,  615,  590,  590,
      622,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      623,  590,  590,  590,  590,  624,  590,  590,  590,  590,

      625,  590,  618,  590,  626,  590,  590,  627,  590,  621,
      590,  590,  628,  590,  590,  590,  590,  590,  629,  590,
      630,  590,  590,  590,  590,  590,  590,  631,  623,  590,
      590,  590,  590,  632,  590,  590,  590,  590,  590,  625,
      590,  590,  626,  633,  590,  627,  590,  590,  634,  590,
      590,  590,  590,  590,  635,  590,  636,  630,  590,  637,
      590,  590,  590,  590,  590,  638,  590,  639,  590,  640,
      590,  590,  641,  632,  590,  590,  590,  590,  590,  590,
      590,  642,  590,  590,  643,  634,  590,  590,  590,  590,
      590,  644,  635,  590,  645,  590,  646,  590,  590,  590,

      590,  590,  638,  590,  647,  590,  648,  590,  649,  590,
      590,  590,  590,  590,  590,  590,  590,  642,  590,  650,
      651,  590,  590,  652,  590,  590,  590,  653,  590,  645,
      590,  654,  646,  590,  655,  590,  590,  590,  590,  656,
      647,  590,  657,  648,  590,  649,  590,  590,  658,  590,
      590,  590,  659,  590,  590,  660,  651,  590,  590,  661,
      590,  662,  590,  653,  590,  663,  590,  664,  590,  590,
      590,  665,  666,  590,  590,  667,  590,  668,  590,  590,
      590,  590,  590,  669,  660,  590,  590,  670,  661,  590,
      671,  590,  663,  590,  672,  664,  590,  590,  590,  665,

      666,  590,  590,  673,  590,  674,  668,  590,  675,  590,
      590,  590,  676,  590,  677,  678,  590,  679,  671,  680,
      590,  590,  681,  590,  590,  590,  682,  673,  683,  590,
      684,  590,  590,  676,  590,  685,  678,  686,  680,  590,
      590,  687,  590,  688,  590,  689,  690,  683,  590,  691,
      684,  590,  692,  685,  686,  590,  590,  693,  687,  590,
      694,  590,  695,  690,  696,  697,  590,  698,  699,  590,
      700,  694,  590,  701,  695,  696,  697,  590,  702,  699,
      703,  704,  590,  705,  702,  703,  704,  706,  706,    0,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,

      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,

      590,  590,  590,  590,  590,  590
    } ;

static yyconst flex_int16_t yy_nxt[1005] =
    {   0,
      590,    5,  590,   97,  482,  590,   77,  129,  142,    6,
      186,  190,    7,    8,    9,   10,   11,   12,   13,   22,
       14,   29,   15,   16,   17,   23,   25,   58,   30,   26,
       59,  199,  249,   18,    5,   98,   78,  130,  143,  254,
      187,  191,    6,   60,  262,    7,    8,    9,   10,   11,
       12,   13,  266,   14,  280,   15,   16,   17,  583,  295,
      312,  200,  250,  318,  378,  327,   18,   64,   65,   66,
      390,  255,  426,   67,  263,   68,  356,  379,  359,  583,
      367,   69,  267,  369,  281,  573,  372,   70,  102,  296,
      313,  103,  104,  319,  105,  328,  384,  391,  106,  107,

      108,  167,  168,  169,  419,  423,  357,  170,  360,  171,
      368,  431,  434,  370,  439,  172,  373,  442,  448,  461,
      416,  173,  454,  475,  483,  487,  385,  392,  494,  505,
      508,  514,  517,  522,  420,  424,  526,  543,  545,  549,
      552,  432,  435,  557,  440,  567,  570,  443,  449,  462,
      573,  583,  570,  476,  484,  488,  567,  248,  495,  506,
      509,  515,  518,  523,  573,  570,  527,  544,  546,  550,
      553,  557,  567,  558,  552,  568,  571,  549,  545,  365,
      574,  584,    4,    4,    4,    4,    4,    4,    4,   19,
       19,   35,   35,   35,   35,   95,   95,  110,  110,  126,

      543,  126,  126,  126,  144,  248,  144,  144,  144,  163,
      163,  182,  182,  201,  557,  201,  201,  201,  211,  211,
      220,  578,  220,  220,  220,  221,  221,  225,  225,  228,
      228,  235,  235,  237,  237,  247,  552,  247,  247,  247,
      259,  259,  549,  259,  259,  261,  261,  264,  526,  264,
      264,  264,  268,  545,  268,  268,  268,  269,  269,  276,
      276,  543,  276,  276,  278,  522,  278,  278,  278,  291,
      291,  301,  301,  303,  303,  248,  303,  303,  305,  305,
      308,  308,  310,  310,  517,  310,  310,  321,  321,  329,
      514,  329,  329,  329,  334,  334,  340,  340,  127,  340,

      340,  343,  508,  343,  343,  343,  346,  365,  346,  346,
      346,  349,  349,  355,  355,  358,  505,  358,  358,  358,
      366,  366,  374,  526,  374,  374,  374,  382,  382,  386,
      562,  386,  386,  386,  393,  560,  393,  393,  393,  395,
      395,  397,  397,  403,  522,  403,  403,  403,  405,  405,
      407,  407,  409,  409,  418,  418,  556,  418,  418,  421,
      421,  428,  428,  430,  494,  430,  430,  430,  433,  517,
      433,  433,  433,  441,  487,  441,  441,  441,  444,  514,
      444,  444,  444,  446,  483,  446,  446,  446,  456,  456,
      457,  508,  457,  457,  457,  460,  460,  464,  505,  464,

      464,  464,  466,  466,  468,  468,  472,  472,  473,  473,
      478,  478,  485,  475,  485,  485,  485,  489,  365,  489,
      489,  489,  491,  491,  493,  541,  493,  493,  493,  496,
      540,  496,  496,  496,  500,  494,  500,  500,  500,  501,
      461,  501,  501,  501,  504,  504,  507,  127,  507,  507,
      507,  513,  513,  516,  516,  519,  487,  519,  519,  519,
      520,  520,  528,  535,  528,  528,  528,  529,  529,  531,
      531,  534,  483,  534,  534,  534,  536,  536,  537,  533,
      537,  537,  537,  538,  538,  539,  532,  539,  539,  539,
      542,  542,  547,  547,  548,  530,  548,  548,  548,  551,

      448,  551,  551,  551,  554,  365,  554,  554,  554,  555,
      475,  555,  555,  555,  559,  525,  559,  559,  559,  561,
      561,  563,  563,  564,  442,  564,  564,  564,  565,  565,
      566,  566,  569,  569,  572,  439,  572,  572,  572,  575,
      524,  575,  575,  575,  576,  521,  576,  576,  576,  577,
      434,  577,  577,  577,  579,  579,  580,  248,  580,  580,
      580,  581,  581,  582,  582,  585,  431,  585,  585,  585,
      586,  461,  586,  586,  586,  587,  423,  587,  587,  587,
      588,  588,  589,  127,  589,  589,  589,  419,  512,  511,
      510,  481,  448,  503,  502,  442,  439,  499,  498,  497,

      434,  431,  492,  391,  490,  423,  486,  384,  419,  481,
      480,  479,  477,  372,  474,  369,  365,  367,  365,  471,
      470,  469,  467,  359,  465,  356,  391,  463,  459,  458,
      384,  455,  417,  453,  452,  451,  450,  447,  372,  445,
      369,  367,  327,  438,  437,  436,  359,  356,  429,  318,
      427,  425,  422,  312,  127,  417,  416,  415,  414,  413,
      412,  411,  410,  295,  365,  408,  406,  404,  327,  402,
      401,  400,  399,  398,  396,  280,  394,  318,  390,  389,
      388,  387,  312,  383,  266,  262,  381,  339,  380,  377,
      376,  375,  295,  371,  249,  365,  364,  363,  362,  361,

      280,  354,  353,  352,  351,  350,  348,  347,  309,  266,
      345,  344,  262,  342,  302,  341,  339,  338,  337,  336,
      335,  333,  332,  331,  330,  249,  289,  326,  325,  324,
      288,  323,  322,  320,  199,  275,  317,  316,  315,  314,
      311,  309,  190,  307,  306,  186,  304,  302,  258,  300,
      299,  298,  297,  294,  293,  292,  290,  289,  248,  288,
      287,  286,  285,  284,  283,  282,  279,  199,  277,  275,
      274,  273,  272,  271,  270,  190,  265,  186,  260,  258,
      142,  257,  256,  253,  252,  251,  248,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  129,  236,  234,  233,

      232,  231,  230,  229,  227,  226,  224,  223,  222,  142,
      219,  218,  217,  216,  215,  214,  213,  212,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  129,  198,  160,
      197,  196,  195,  159,  194,  193,  192,  189,  188,  185,
      184,  183,   77,  181,  180,  179,  178,  177,  176,  175,
      174,  166,  165,  164,  162,  161,  160,  127,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,   77,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  128,  127,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,

      112,  111,  109,  101,  100,   99,   96,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   79,   76,   75,   74,   73,   72,   71,   63,
       62,   61,   57,   56,   55,   54,   53,   52,   36,   51,
       50,   49,   48,   47,   46,   45,   44,   43,   42,   41,
       40,   39,   38,   37,   36,   34,   33,   32,   31,   28,
       27,   24,   21,   20,  590,    3,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,

      590,  590,  590,  590
    } ;

static yyconst flex_int16_t yy_chk[1005] =
    {   0,
        0,    1,    0,   72,  659,    0,   53,   97,  109,    1,
      148,  151,    1,    1,    1,    1,    1,    1,    1,    9,
        1,   14,    1,    1,    1,    9,   11,   42,   14,   11,
       42,  162,  212,    1,    2,   72,   53,   97,  109,  216,
      148,  151,    2,   42,  224,    2,    2,    2,    2,    2,
        2,    2,  227,    2,  239,    2,    2,    2,  589,  254,
      271,  162,  212,  279,  338,  290,    2,   46,   46,   46,
      390,  216,  390,   46,  224,   46,  320,  338,  322,  588,
      330,   46,  227,  331,  239,  587,  333,   46,   76,  254,
      271,   76,   76,  279,   76,  290,  348,  354,   76,   76,

       76,  134,  134,  134,  383,  388,  320,  134,  322,  134,
      330,  396,  398,  331,  404,  134,  333,  406,  411,  425,
      416,  134,  416,  447,  455,  459,  348,  354,  467,  477,
      479,  486,  490,  498,  383,  388,  503,  524,  525,  530,
      535,  396,  398,  541,  404,  556,  560,  406,  411,  425,
      562,  578,  586,  447,  455,  459,  585,  583,  467,  477,
      479,  486,  490,  498,  582,  581,  503,  524,  525,  530,
      535,  580,  579,  541,  577,  556,  560,  576,  575,  573,
      562,  578,  591,  591,  591,  591,  591,  591,  591,  592,
      592,  593,  593,  593,  593,  594,  594,  595,  595,  596,

      572,  596,  596,  596,  597,  570,  597,  597,  597,  598,
      598,  599,  599,  600,  569,  600,  600,  600,  601,  601,
      602,  567,  602,  602,  602,  603,  603,  604,  604,  605,
      605,  606,  606,  607,  607,  608,  566,  608,  608,  608,
      609,  609,  565,  609,  609,  610,  610,  611,  564,  611,
      611,  611,  612,  563,  612,  612,  612,  613,  613,  614,
      614,  561,  614,  614,  615,  559,  615,  615,  615,  616,
      616,  617,  617,  618,  618,  557,  618,  618,  619,  619,
      620,  620,  621,  621,  555,  621,  621,  622,  622,  623,
      554,  623,  623,  623,  624,  624,  625,  625,  552,  625,

      625,  626,  551,  626,  626,  626,  627,  549,  627,  627,
      627,  628,  628,  629,  629,  630,  548,  630,  630,  630,
      631,  631,  632,  547,  632,  632,  632,  633,  633,  634,
      545,  634,  634,  634,  635,  543,  635,  635,  635,  636,
      636,  637,  637,  638,  542,  638,  638,  638,  639,  639,
      640,  640,  641,  641,  642,  642,  540,  642,  642,  643,
      643,  644,  644,  645,  539,  645,  645,  645,  646,  538,
      646,  646,  646,  647,  537,  647,  647,  647,  648,  536,
      648,  648,  648,  649,  534,  649,  649,  649,  650,  650,
      651,  531,  651,  651,  651,  652,  652,  653,  529,  653,

      653,  653,  654,  654,  655,  655,  656,  656,  657,  657,
      658,  658,  660,  528,  660,  660,  660,  661,  526,  661,
      661,  661,  662,  662,  663,  522,  663,  663,  663,  664,
      521,  664,  664,  664,  665,  520,  665,  665,  665,  666,
      519,  666,  666,  666,  667,  667,  668,  517,  668,  668,
      668,  669,  669,  670,  670,  671,  516,  671,  671,  671,
      672,  672,  673,  514,  673,  673,  673,  674,  674,  675,
      675,  676,  513,  676,  676,  676,  677,  677,  678,  512,
      678,  678,  678,  679,  679,  680,  511,  680,  680,  680,
      681,  681,  682,  682,  683,  508,  683,  683,  683,  684,

      507,  684,  684,  684,  685,  505,  685,  685,  685,  686,
      504,  686,  686,  686,  687,  502,  687,  687,  687,  688,
      688,  689,  689,  690,  501,  690,  690,  690,  691,  691,
      692,  692,  693,  693,  694,  500,  694,  694,  694,  695,
      499,  695,  695,  695,  696,  497,  696,  696,  696,  697,
      496,  697,  697,  697,  698,  698,  699,  494,  699,  699,
      699,  700,  700,  701,  701,  702,  493,  702,  702,  702,
      703,  491,  703,  703,  703,  704,  489,  704,  704,  704,
      705,  705,  706,  487,  706,  706,  706,  485,  483,  482,
      481,  480,  478,  475,  474,  473,  472,  471,  470,  469,

      468,  466,  465,  464,  461,  460,  458,  457,  456,  452,
      451,  450,  448,  446,  445,  444,  442,  441,  439,  438,
      437,  436,  434,  433,  431,  430,  428,  427,  423,  422,
      421,  419,  418,  415,  414,  413,  412,  410,  409,  408,
      407,  405,  403,  401,  400,  399,  397,  395,  394,  393,
      391,  389,  387,  386,  384,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  372,  371,  369,  367,  366,  365,
      364,  363,  362,  361,  359,  358,  356,  355,  353,  352,
      351,  350,  349,  347,  346,  343,  341,  340,  339,  337,
      336,  335,  334,  332,  329,  327,  326,  325,  324,  323,

      321,  318,  317,  316,  315,  314,  312,  311,  310,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  295,  294,  293,  292,  291,  288,  287,  286,  285,
      284,  283,  282,  280,  278,  276,  275,  274,  273,  272,
      270,  269,  268,  266,  265,  264,  262,  261,  259,  258,
      257,  256,  255,  253,  252,  251,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  228,  226,  225,  222,  221,
      220,  218,  217,  215,  214,  213,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  199,  197,  196,

      195,  194,  193,  192,  190,  188,  186,  185,  184,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  161,  159,
      158,  157,  156,  155,  154,  153,  152,  150,  149,  147,
      146,  145,  144,  142,  141,  140,  139,  138,  137,  136,
      135,  133,  132,  131,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   86,   85,   83,   82,   81,

       80,   79,   77,   75,   74,   73,   71,   69,   68,   67,
       66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
       56,   55,   54,   52,   51,   50,   49,   48,   47,   45,
       44,   43,   41,   40,   39,   38,   37,   36,   35,   34,
       33,   32,   31,   30,   29,   28,   27,   26,   25,   24,
       23,   22,   21,   20,   19,   18,   17,   16,   15,   13,
       12,   10,    8,    7,    3,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,

      590,  590,  590,  590
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#line 890 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "compiler.l"


#line 1075 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 591 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 966 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "compiler.l"
printf("Token INTEGER: %s\n", yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "compiler.l"
printf("Token CHARACTER: %s\n", yytext);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "compiler.l"
printf("Token BOOLEAN: %s\n", yytext);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "compiler.l"
printf("Token CONSTANT: %s\n", yytext);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "compiler.l"
printf("Token FUNCTION: %s\n", yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "compiler.l"
printf("Token ENDFUNCTION: %s\n", yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "compiler.l"
printf("Token VAR_DEFINITION: %s\n", yytext);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "compiler.l"
printf("Token LESS_THAN: %s\n", yytext);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "compiler.l"
printf("Token GREATER_THAN: %s\n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "compiler.l"
printf("Token EQUALS: %s\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "compiler.l"
printf("Token NOT_EQUALS: %s\n", yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "compiler.l"
printf("Token IF: %s\n", yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "compiler.l"
printf("Token ENDIF: %s\n", yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "compiler.l"
printf("Token WHILE: %s\n", yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "compiler.l"
printf("Token ENDWHILE: %s\n", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "compiler.l"
printf("Token ADD: %s\n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "compiler.l"
printf("Token LESS: %s\n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "compiler.l"
printf("Token DIVIDE: %s\n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "compiler.l"
printf("Token MULTIPLY: %s\n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "compiler.l"
printf("NO ES UN TOKEN\n");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "compiler.l"
ECHO;
	YY_BREAK
#line 1263 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 591 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 591 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 590);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 48 "compiler.l"




int
main(int argc, char *argv[]) {
   yylex();
}

