PARA COMPILAR PARARSE EN EL DIRECTORIO COMPILER Y EJECUTAR
EL SCRIPT COMPILE.
SE GENERARA EL EJECUTABLE COMPILER.

PARA USAR EL COMPILADOR SE DEBE EJECUTAR EL COMANDO

	> compiler input [-o output]

DONDE INPUT ES EL PATH AL ARCHIVO DE ENTRADA Y SE PUEDE ESPECIFICAR EL 
ARCHIVO DE SALIDA AGREGANDO -o output, DONDE OUTPUT ES EL PATH DEL 
ARCHIVO DE SALIDA. SI NO SE ESPECIFICA EL ARCHIVO DE SALIDA SE GENERARA 
EL ARCHIVO out.c.

EL COMPILADOR GENERA CODIGO C LISTO PARA SER COMPILADO.

DE ESPECIFICARSE UN ARCHIVO DE SALIDA, ESTE DEBE TENER LA EXTENSION .c PARA
QUE LUEGO UN COMPILADOR DE C LO PUEDA ENTENDER.
